Fix install directions: `mkdir` before `cp` to it
Without this line, since the plugins directory does not exist, the
`cp` command a few lines later will copy the metabase-datomic uberjar
to a file named "plugins" instead of into a directory of that
name. This causes `lein run -m metabase.core` to fail with an error
like:

   05-28 11:47:24 ERROR metabase.core :: Metabase Initialization FAILED
   java.nio.file.NotDirectoryException: /path/to/metabase/plugins
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
	at java.base/java.nio.file.Files.list(Files.java:3694)
	at metabase.plugins.files$files_seq.invokeStatic(files.clj:68)
	at metabase.plugins.files$files_seq.invoke(files.clj:65)
	at metabase.plugins$plugins_paths.invokeStatic(plugins.clj:92)
	at metabase.plugins$plugins_paths.invoke(plugins.clj:91)
	at metabase.plugins$load_plugins_BANG_.invokeStatic(plugins.clj:136)
	at metabase.plugins$load_plugins_BANG_.invoke(plugins.clj:121)
	at metabase.core$init_BANG_.invokeStatic(core.clj:66)
	at metabase.core$init_BANG_.invoke(core.clj:54)
	at metabase.core$start_normally.invokeStatic(core.clj:121)
	at metabase.core$start_normally.invoke(core.clj:115)
	at metabase.core$_main.invokeStatic(core.clj:141)
	at metabase.core$_main.doInvoke(core.clj:136)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:380)
	at user$eval163.invokeStatic(form-init14013909902028734341.clj:1)
	at user$eval163.invoke(form-init14013909902028734341.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)